--function 
create function get_film_count(len_from int, len_to int
	return int
	langue as
		$$)

        $$





--foreign key



on delete set null
create table streets(
stree_id serial primary key,
city_id int not null)
ins
constraint fx_city_id
foregin

 create table cities(
 city_id serial Primary key,
 city_name varchar(50) not null)
 
 insert into cities(cit_name
)
 
 
 
create table colors (
	
color_id int generated by default as identity,
color_name vachar(50)notn ull)

create table colors (
color_id int generated always as identity
color_name varchar(50)not null) 


create table color;(
color- id serial primary key,
color_name varchar(50) not null)


